-- Compiled schema (compact)
-- Generated: combines core CREATE TABLE statements used by the application

CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(100) NOT NULL UNIQUE, email VARCHAR(255) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, full_name VARCHAR(150), role VARCHAR(50) DEFAULT 'user', status ENUM('active','inactive','pending') NOT NULL DEFAULT 'active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS communities (id INT AUTO_INCREMENT PRIMARY KEY, community_code VARCHAR(20) NOT NULL UNIQUE, name VARCHAR(150) NOT NULL, area VARCHAR(80) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS batches (id INT AUTO_INCREMENT PRIMARY KEY, batch_code VARCHAR(20) NOT NULL UNIQUE, community_id INT NOT NULL, name VARCHAR(150) NOT NULL, records INT NOT NULL DEFAULT 0, progress INT NOT NULL DEFAULT 0, status VARCHAR(20) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (community_id) REFERENCES communities(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS groups (id INT AUTO_INCREMENT PRIMARY KEY, group_code VARCHAR(20) NOT NULL UNIQUE, community_id INT NOT NULL, name VARCHAR(150) NOT NULL, leader VARCHAR(150), members_count INT NOT NULL DEFAULT 0, status VARCHAR(20) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (community_id) REFERENCES communities(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS group_batch (group_id INT NOT NULL, batch_id INT NOT NULL, PRIMARY KEY (group_id, batch_id), FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE, FOREIGN KEY (batch_id) REFERENCES batches(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS mothers (id INT AUTO_INCREMENT PRIMARY KEY, mother_code VARCHAR(20) NOT NULL UNIQUE, community_id INT NOT NULL, group_id INT NULL, batch_id INT NULL, first_name VARCHAR(100) NOT NULL, middle_name VARCHAR(100), last_name VARCHAR(100) NOT NULL, suffix VARCHAR(20), mother_id_no VARCHAR(50) UNIQUE, dob DATE, lmp_date DATE, edd_date DATE, contact_number VARCHAR(20), is_high_risk BOOLEAN DEFAULT FALSE, program_type VARCHAR(150), emergency_name VARCHAR(150), emergency_contact VARCHAR(20), emergency_relationship VARCHAR(60), spouse_name VARCHAR(150), address TEXT, prenatal_reg_date DATE, trimester VARCHAR(30), gestational_age INT, prenatal_weight DECIMAL(5,2), prenatal_bp VARCHAR(20), prenatal_height VARCHAR(20), fundal_height VARCHAR(20), fhr VARCHAR(20), gravida INT, para INT, abortion INT DEFAULT 0, stillbirth INT DEFAULT 0, status VARCHAR(20) DEFAULT 'Active', visits INT DEFAULT 0, progress INT DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (community_id) REFERENCES communities(id) ON DELETE CASCADE, FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE SET NULL, FOREIGN KEY (batch_id) REFERENCES batches(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS mother_ob_history (id INT AUTO_INCREMENT PRIMARY KEY, mother_id INT NOT NULL, event_code VARCHAR(20) NOT NULL, gestational_age VARCHAR(50), outcome TEXT, FOREIGN KEY (mother_id) REFERENCES mothers(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS mother_medical_conditions (id INT AUTO_INCREMENT PRIMARY KEY, mother_id INT NOT NULL, condition_name VARCHAR(80) NOT NULL, has_condition BOOLEAN NOT NULL DEFAULT FALSE, FOREIGN KEY (mother_id) REFERENCES mothers(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS mother_dental_records (id INT AUTO_INCREMENT PRIMARY KEY, mother_id INT NOT NULL, dental_facility VARCHAR(150), dentist_in_charge VARCHAR(150), community_dentist VARCHAR(150), dentist_license VARCHAR(80), dentist_contact VARCHAR(20), teeth_count INT, dental_findings TEXT, dental_remarks TEXT, tartar_removal BOOLEAN DEFAULT FALSE, filling BOOLEAN DEFAULT FALSE, cleaning BOOLEAN DEFAULT FALSE, extraction BOOLEAN DEFAULT FALSE, root_canal BOOLEAN DEFAULT FALSE, other_procedure BOOLEAN DEFAULT FALSE, FOREIGN KEY (mother_id) REFERENCES mothers(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS mother_vaccinations (id INT AUTO_INCREMENT PRIMARY KEY, mother_id INT NOT NULL, vaccine_name VARCHAR(20) NOT NULL, vaccine_date DATE, remarks TEXT, FOREIGN KEY (mother_id) REFERENCES mothers(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS children (id INT AUTO_INCREMENT PRIMARY KEY, child_code VARCHAR(30) NOT NULL UNIQUE, mother_id INT NOT NULL, community_id INT NULL, batch_id INT NULL, first_name VARCHAR(120) NOT NULL, middle_name VARCHAR(120), last_name VARCHAR(120) NOT NULL, suffix VARCHAR(30), birth_date DATE, birth_weight DECIMAL(5,2), birth_length DECIMAL(5,2), gender ENUM('Male','Female','Other') DEFAULT 'Female', delivery_type VARCHAR(80), health_status VARCHAR(120), birth_place VARCHAR(150), birth_attendant VARCHAR(150), apgar_score VARCHAR(10), feeding_type VARCHAR(80), nutrition_notes TEXT, father_name VARCHAR(150), relationship VARCHAR(50), address TEXT, progress INT DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (mother_id) REFERENCES mothers(id) ON DELETE CASCADE, FOREIGN KEY (community_id) REFERENCES communities(id) ON DELETE SET NULL, FOREIGN KEY (batch_id) REFERENCES batches(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS child_medical_conditions (id INT AUTO_INCREMENT PRIMARY KEY, child_id INT NOT NULL, condition_name VARCHAR(80) NOT NULL, has_condition BOOLEAN NOT NULL DEFAULT FALSE, FOREIGN KEY (child_id) REFERENCES children(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS child_vaccinations (id INT AUTO_INCREMENT PRIMARY KEY, child_id INT NOT NULL, vaccine_name VARCHAR(50) NOT NULL, vaccine_date DATE, remarks TEXT, FOREIGN KEY (child_id) REFERENCES children(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS child_checkups (id INT AUTO_INCREMENT PRIMARY KEY, child_id INT NOT NULL, checkup_date DATE, weight DECIMAL(5,2), height DECIMAL(5,2), notes TEXT, FOREIGN KEY (child_id) REFERENCES children(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- End of compiled schema
